### PR TITLE
Symfony 3 support + fixes

### PR DESCRIPTION
**Pull request by ghost**
I've been using this fork for 3 weeks now and it works just fine. 

Please merge this so that Symfony 3 support is added.

### CODE REVIEW

**Comment by ghost** [comment]
@bezhermoso Please merge this so that we can use this on Symfony 3 without having to mess around with composer.

**Comment by vsmoraes** [comment]
👍  we need this

**Comment by IlyaPokamestov** [comment]
@bezhermoso @jwestman-activelamp @tomfriedhof guys what should be done to merge this one? I can continue this PR if that needed.
Thanks!

**Comment by bezhermoso** [comment]
Hi all,

I haven't checked up on this repo for quite a while now. I will take a closer look at issues/PRs early December; I'd like to get this upgraded for Symfony 3 as well. This might have to wait until after we get the Travis builds in place and have the test pass again. What do you guys think?

**Comment by vsmoraes** [comment]
Awesome! I'm working on a brand new project and soon this feature will be a necessary. You can count on me if any kind of help is needed o/

**Comment by ghost** [comment]
@bezhermoso It would be good to have Travis in place, but this merge is pretty important in my opinion. I've been using this fork for a while now, but I prefer to use the original repo (which I can only do once this PR has been merged / this project has been upgraded to Symfony3).

**Pull request merged**
